In [1]:
import polars as pl

path = './Files/Sample_Superstore.csv'

df = pl.read_csv(path)
df.head()

shape: (5, 21)
┌────────┬───────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Row_ID ┆ Order_ID      ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit   │
│ ---    ┆ ---           ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64    ┆ str           ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64      │
╞════════╪═══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ null          ┆ null       ┆ 11-11-2016 ┆ … ┆ 261.96   ┆ 2        ┆ 0.0      ┆ 41.9136  │
│ 2      ┆ CA-2016-15215 ┆ 08-11-2016 ┆ 11-11-2016 ┆ … ┆ 731.94   ┆ 3        ┆ 0.0      ┆ 219.582  │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 3      ┆ CA-2016-13868 ┆ 12-06-2016 ┆ null       ┆ … ┆ 14.62    ┆ 2        ┆ 0.0      ┆ 6.8714   │
│        ┆ 8             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
│ 4      ┆ null          ┆ 11-10-2015 ┆ null       ┆ … ┆ 957.5775 ┆ 5        ┆ 0.45     ┆ -383.031 │
│ 5      ┆ US-2015-10896 ┆ 11-10-2015 ┆ 18-10-2015 ┆ … ┆ 22.368   ┆ 2        ┆ 0.2      ┆ 2.5164   │
│        ┆ 6             ┆            ┆            ┆   ┆          ┆          ┆          ┆          │
└────────┴───────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [2]:
df.tail(5)

shape: (5, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬─────────┬──────────┬──────────┬─────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales   ┆ Quantity ┆ Discount ┆ Profit  │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---     ┆ ---      ┆ ---      ┆ ---     │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64     ┆ i64      ┆ f64      ┆ f64     │
╞════════╪════════════════╪════════════╪════════════╪═══╪═════════╪══════════╪══════════╪═════════╡
│ 9990   ┆ CA-2014-110422 ┆ 21-01-2014 ┆ 23-01-2014 ┆ … ┆ 25.248  ┆ 3        ┆ 0.2      ┆ 4.1028  │
│ 9991   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 91.96   ┆ 2        ┆ 0.0      ┆ 15.6332 │
│ 9992   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 258.576 ┆ 2        ┆ 0.2      ┆ 19.3932 │
│ 9993   ┆ CA-2017-121258 ┆ 26-02-2017 ┆ 03-03-2017 ┆ … ┆ 29.6    ┆ 4        ┆ 0.0      ┆ 13.32   │
│ 9994   ┆ CA-2017-119914 ┆ 04-05-2017 ┆ 09-05-2017 ┆ … ┆ 243.16  ┆ 2        ┆ 0.0      ┆ 72.948  │
└────────┴────────────────┴────────────┴────────────┴───┴─────────┴──────────┴──────────┴─────────┘

In [3]:
df.columns

['Row_ID',
 'Order_ID',
 'Order_Date',
 'Ship_Date',
 'Ship_Mode',
 'Customer_ID',
 'Customer_Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal_Code',
 'Region',
 'Product_ID',
 'Category',
 'Sub_Category',
 'Product_Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [4]:
df['Customer_Name']

shape: (9_994,)
Series: 'Customer_Name' [str]
[
	"Claire Gute"
	"Claire Gute"
	"Darrin Van Huff"
	"Sean O'Donnell"
	"Sean O'Donnell"
	…
	"Tom Boeckenhauer"
	"Dave Brooks"
	"Dave Brooks"
	"Dave Brooks"
	"Chris Cortes"
]

In [7]:
print(type(df['Customer_Name']))
print(type(df[['Customer_Name']]))
df[['Customer_Name']].dtypes

<class 'polars.series.series.Series'>
<class 'polars.dataframe.frame.DataFrame'>

[String]

In [10]:
json_df = pl.read_json('./Files/Second.json')
json_df

shape: (12_407, 4)
┌──────────────┬──────────────┬──────┬─────────────┐
│ Country Name ┆ Country Code ┆ Year ┆ Value       │
│ ---          ┆ ---          ┆ ---  ┆ ---         │
│ str          ┆ str          ┆ str  ┆ str         │
╞══════════════╪══════════════╪══════╪═════════════╡
│ Arab World   ┆ ARB          ┆ 1960 ┆ 96388069    │
│ Arab World   ┆ ARB          ┆ 1961 ┆ 98882541.4  │
│ Arab World   ┆ ARB          ┆ 1962 ┆ 101474075.8 │
│ Arab World   ┆ ARB          ┆ 1963 ┆ 104169209.2 │
│ Arab World   ┆ ARB          ┆ 1964 ┆ 106978104.6 │
│ …            ┆ …            ┆ …    ┆ …           │
│ Zimbabwe     ┆ ZWE          ┆ 2006 ┆ 12529655    │
│ Zimbabwe     ┆ ZWE          ┆ 2007 ┆ 12481245    │
│ Zimbabwe     ┆ ZWE          ┆ 2008 ┆ 12451543    │
│ Zimbabwe     ┆ ZWE          ┆ 2009 ┆ 12473992    │
│ Zimbabwe     ┆ ZWE          ┆ 2010 ┆ 12571000    │
└──────────────┴──────────────┴──────┴─────────────┘

In [12]:
json_df.columns
print(json_df.shape) #Rows,colums

(12407, 4)

In [15]:
json_df[['Country Name']].dtypes

[String]

In [18]:
#lazy = pl.scan_parquet   can read multiple files at once
# Accepts file paths, lists of paths, or glob patterns (e.g., "data/*.csv") to scan multiple files together.
# returns lazy dataframe
lf = pl.lazyframe.LazyFrame({'Values':[0, 1, 2]})
lf

In [19]:
jsn_df = pl.read_json('./Files/Third.json')
jsn_df

shape: (1, 4)
┌───────┬─────┬─────────┬─────────────────────────────────┐
│ name  ┆ age ┆ address ┆ friends                         │
│ ---   ┆ --- ┆ ---     ┆ ---                             │
│ str   ┆ i64 ┆ str     ┆ list[struct[2]]                 │
╞═══════╪═════╪═════════╪═════════════════════════════════╡
│ Chris ┆ 23  ┆ America ┆ [{"Emily",["biking", "music", … │
└───────┴─────┴─────────┴─────────────────────────────────┘

In [20]:
jsn_df.schema

Schema([('name', String),
        ('age', Int64),
        ('address', String),
        ('friends', List(Struct({'name': String, 'hobbies': List(String)})))])

In [24]:
expl = jsn_df.explode('friends', empty_as_null=True)
expl

shape: (2, 4)
┌───────┬─────┬─────────┬─────────────────────────────────┐
│ name  ┆ age ┆ address ┆ friends                         │
│ ---   ┆ --- ┆ ---     ┆ ---                             │
│ str   ┆ i64 ┆ str     ┆ struct[2]                       │
╞═══════╪═════╪═════════╪═════════════════════════════════╡
│ Chris ┆ 23  ┆ America ┆ {"Emily",["biking", "music", "… │
│ Chris ┆ 23  ┆ America ┆ {"John",["soccer", "gaming"]}   │
└───────┴─────┴─────────┴─────────────────────────────────┘

In [25]:
expl.with_columns(
    pl.col('friends').struct.field('name').alias('friend_name'),
    pl.col('friends').struct.field('hobbies').alias('friend_hobbies')
)

shape: (2, 6)
┌───────┬─────┬─────────┬─────────────────────┬─────────────┬───────────────────────────────┐
│ name  ┆ age ┆ address ┆ friends             ┆ friend_name ┆ friend_hobbies                │
│ ---   ┆ --- ┆ ---     ┆ ---                 ┆ ---         ┆ ---                           │
│ str   ┆ i64 ┆ str     ┆ struct[2]           ┆ str         ┆ list[str]                     │
╞═══════╪═════╪═════════╪═════════════════════╪═════════════╪═══════════════════════════════╡
│ Chris ┆ 23  ┆ America ┆ {"Emily",["biking", ┆ Emily       ┆ ["biking", "music", "gaming"] │
│       ┆     ┆         ┆ "music", "…         ┆             ┆                               │
│ Chris ┆ 23  ┆ America ┆ {"John",["soccer",  ┆ John        ┆ ["soccer", "gaming"]          │
│       ┆     ┆         ┆ "gaming"]}          ┆             ┆                               │
└───────┴─────┴─────────┴─────────────────────┴─────────────┴───────────────────────────────┘

```
import polars as pl

# Sample DataFrame
df = pl.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "salary": [50000, 60000, 70000]
})

# 1. Add a single new column using keyword arguments
df_new = df.with_columns(
    bonus = pl.col("salary") * 0.1
)

# 2. Add multiple columns at once using positional arguments
df_multi = df.with_columns(
    (pl.col("age") + 1).alias("age_next_year"),
    (pl.col("salary") / 12).alias("monthly_pay")
)

# 3. Overwrite an existing column
df_modified = df.with_columns(
    age = pl.col("age") + 5
)
```

In [27]:
#WRITE FILES
data = {
   'Name': ['Alice', 'Bob', 'Bob', 'Bob', 'Alice'],
   'Age': [23, None, 30,  None,  None],
    'Score': [85, 90, None, 88, 92]
}
df = pl.DataFrame(data)
df

shape: (5, 3)
┌───────┬──────┬───────┐
│ Name  ┆ Age  ┆ Score │
│ ---   ┆ ---  ┆ ---   │
│ str   ┆ i64  ┆ i64   │
╞═══════╪══════╪═══════╡
│ Alice ┆ 23   ┆ 85    │
│ Bob   ┆ null ┆ 90    │
│ Bob   ┆ 30   ┆ null  │
│ Bob   ┆ null ┆ 88    │
│ Alice ┆ null ┆ 92    │
└───────┴──────┴───────┘

In [29]:
df.write_csv('./Files/output.csv')

In [30]:
df.write_json('./Files/output.json')
df.write_parquet('./Files/output.parquet')