In [1]:
!pip install sqlite-utils

Collecting sqlite-utils
  Downloading sqlite_utils-4.1.1-py3-none-any.whl.metadata (6.8 kB)
Collecting click>=8.3.1 (from sqlite-utils)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting click-default-group>=1.2.3 (from sqlite-utils)
  Downloading click_default_group-1.2.4-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: pluggy in c:\users\sholar\anaconda3\lib\site-packages (from sqlite-utils) (1.5.0)
Requirement already satisfied: python-dateutil in c:\users\sholar\anaconda3\lib\site-packages (from sqlite-utils) (2.9.0.post0)
Collecting sqlite-fts4 (from sqlite-utils)
  Downloading sqlite_fts4-1.0.3-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: tabulate in c:\users\sholar\anaconda3\lib\site-packages (from sqlite-utils) (0.9.0)
Requirement already satisfied: pip in c:\users\sholar\anaconda3\lib\site-packages (from sqlite-utils) (25.3)
Requirement already satisfied: colorama in c:\users\sholar\anaconda3\lib\site-packages (from click>=8.3.1->sqlite-utils) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\sholar\anaconda3\lib\site-packages (from python-dateutil->sqlite-utils) (1.17.0)
Downloading sqlite_utils-4.1.1-py3-none-any.whl (89 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading click_default_group-1.2.4-py2.py3-none-any.whl (4.1 kB)
Downloading sqlite_fts4-1.0.3-py3-none-any.whl (10.0 kB)
Installing collected packages: sqlite-fts4, click, click-default-group, sqlite-utils

  Attempting uninstall: click

    Found existing installation: click 8.2.1

    Uninstalling click-8.2.1:

      Successfully uninstalled click-8.2.1

   ---------- ----------------------------- 1/4 [click]
   ---------- ----------------------------- 1/4 [click]
   ------------------------------ --------- 3/4 [sqlite-utils]
   ---------------------------------------- 4/4 [sqlite-utils]

Successfully installed click-8.4.2 click-default-group-1.2.4 sqlite-fts4-1.0.3 sqlite-utils-4.1.1

In [3]:
import sqlite3
import polars as pl
from pathlib import Path

file_loc = './Files/Sample_Superstore.csv'
sqlite_dir = Path('./Files/sqlite/Sample_Superstore')
df = pl.read_csv(file_loc)

In [4]:
if not sqlite_dir.exists():
    sqlite_dir.mkdir(parents=True, exist_ok=True)
sqlite_file = sqlite_dir / 'sample_store.sqlite'

In [6]:
uri = 'sqlite:///' + sqlite_file.as_posix()
uri

'sqlite:///Files/sqlite/Sample_Superstore/sample_store.sqlite'

In [8]:
if sqlite_dir.exists():
    (
        df.sort('Customer_ID')
        .write_database(
            table_name='records',
            connection=uri,
            if_table_exists='replace',
            engine='sqlalchemy'
        )
    )

In [10]:
!pip install adbc-driver-manager

Collecting adbc-driver-manager
  Downloading adbc_driver_manager-1.12.0-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: typing-extensions in c:\users\sholar\anaconda3\lib\site-packages (from adbc-driver-manager) (4.15.0)
Downloading adbc_driver_manager-1.12.0-cp313-cp313-win_amd64.whl (758 kB)
   ---------------------------------------- 0.0/758.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/758.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/758.9 kB ? eta -:--:--
   ------------- -------------------------- 262.1/758.9 kB ? eta -:--:--
   --------------------------- ------------ 524.3/758.9 kB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 758.9/758.9 kB 1.9 MB/s  0:00:00
Installing collected packages: adbc-driver-manager
Successfully installed adbc-driver-manager-1.12.0

In [12]:
!pip install adbc-driver-sqlite

Collecting adbc-driver-sqlite
  Downloading adbc_driver_sqlite-1.12.0-py3-none-win_amd64.whl.metadata (3.6 kB)
Requirement already satisfied: adbc-driver-manager in c:\users\sholar\anaconda3\lib\site-packages (from adbc-driver-sqlite) (1.12.0)
Collecting importlib-resources>=1.3 (from adbc-driver-sqlite)
  Downloading importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: typing-extensions in c:\users\sholar\anaconda3\lib\site-packages (from adbc-driver-manager->adbc-driver-sqlite) (4.15.0)
Downloading adbc_driver_sqlite-1.12.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.5 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.7 MB/s  0:00:01
Downloading importlib_resources-7.1.0-py3-none-any.whl (37 kB)
Installing collected packages: importlib-resources, adbc-driver-sqlite

   -------------------- ------------------- 1/2 [adbc-driver-sqlite]
   ---------------------------------------- 2/2 [adbc-driver-sqlite]

Successfully installed adbc-driver-sqlite-1.12.0 importlib-resources-7.1.0

In [13]:
dfb = pl.read_database_uri('select * from records limit 3', uri=uri, engine='adbc') 
dfb

shape: (3, 21)
┌────────┬────────────────┬────────────┬────────────┬───┬────────┬──────────┬──────────┬────────┐
│ Row_ID ┆ Order_ID       ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales  ┆ Quantity ┆ Discount ┆ Profit │
│ ---    ┆ ---            ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---    │
│ i64    ┆ str            ┆ str        ┆ str        ┆   ┆ f64    ┆ i64      ┆ f64      ┆ f64    │
╞════════╪════════════════╪════════════╪════════════╪═══╪════════╪══════════╪══════════╪════════╡
│ 1160   ┆ CA-2017-147039 ┆ 29-06-2017 ┆ 04-07-2017 ┆ … ┆ 362.94 ┆ 3        ┆ 0.0      ┆ 90.735 │
│ 1161   ┆ CA-2017-147039 ┆ 29-06-2017 ┆ 04-07-2017 ┆ … ┆ 11.54  ┆ 2        ┆ 0.0      ┆ 5.77   │
│ 1300   ┆ CA-2015-121391 ┆ 04-10-2015 ┆ 07-10-2015 ┆ … ┆ 26.96  ┆ 2        ┆ 0.0      ┆ 7.0096 │
└────────┴────────────────┴────────────┴────────────┴───┴────────┴──────────┴──────────┴────────┘

In [14]:
dfb = pl.read_database_uri('select * from records', uri=uri, engine='adbc') 
dfb.shape

(9994, 21)

In [17]:
dfb.filter(pl.col('Profit') > 1000).head()

shape: (5, 21)
┌────────┬──────────────┬────────────┬────────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ Row_ID ┆ Order_ID     ┆ Order_Date ┆ Ship_Date  ┆ … ┆ Sales    ┆ Quantity ┆ Discount ┆ Profit    │
│ ---    ┆ ---          ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ i64    ┆ str          ┆ str        ┆ str        ┆   ┆ f64      ┆ i64      ┆ f64      ┆ f64       │
╞════════╪══════════════╪════════════╪════════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 354    ┆ CA-2016-1297 ┆ 01-09-2016 ┆ 03-09-2016 ┆ … ┆ 4355.168 ┆ 4        ┆ 0.2      ┆ 1415.4296 │
│        ┆ 14           ┆            ┆            ┆   ┆          ┆          ┆          ┆           │
│ 9040   ┆ CA-2016-1171 ┆ 17-12-2016 ┆ 21-12-2016 ┆ … ┆ 9892.74  ┆ 13       ┆ 0.0      ┆ 4946.37   │
│        ┆ 21           ┆            ┆            ┆   ┆          ┆          ┆          ┆           │
│ 516    ┆ CA-2017-1274 ┆ 22-01-2017 ┆ 27-01-2017 ┆ … ┆ 2999.95  ┆ 5        ┆ 0.0      ┆ 1379.977  │
│        ┆ 32           ┆            ┆            ┆   ┆          ┆          ┆          ┆           │
│ 6521   ┆ CA-2017-1382 ┆ 16-01-2017 ┆ 18-01-2017 ┆ … ┆ 5443.96  ┆ 4        ┆ 0.0      ┆ 2504.2216 │
│        ┆ 89           ┆            ┆            ┆   ┆          ┆          ┆          ┆           │
│ 4278   ┆ US-2016-1074 ┆ 16-04-2016 ┆ 20-04-2016 ┆ … ┆ 9099.93  ┆ 7        ┆ 0.0      ┆ 2365.9818 │
│        ┆ 40           ┆            ┆            ┆   ┆          ┆          ┆          ┆           │
└────────┴──────────────┴────────────┴────────────┴───┴──────────┴──────────┴──────────┴───────────┘

In [ ]:
df.c