In [1]:
import pandas as pd
houses = pd.read_csv('../data/kc_house_data.csv')
titanic = pd.read_csv('../data/titanic.csv')
netflix = pd.read_csv('../data/netflix_titles.csv', sep='|', index_col=0)
btc = pd.read_csv('../data/coin_Bitcoin.csv')
countries = pd.read_csv('../data/world-happiness-report-2021.csv')

In [2]:
countries.set_index("Country name", inplace=True)

In [3]:
btc.drop(['Name', 'Symbol', 'SNo'], axis=1) #inpace=True first arg = labels  default axis = 0 deletes rows
#df.drop(['Col1', 'Col2'], axis=1 or columns)    or df.drop(columns=['Col1', 'Col2'])
#df.drop(index=[0, 1]) df.drop([0, 1], axis=0) 0 and 1 are labels might be string

,Date,High,Low,Open,Close,Volume,Marketcap
0,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09
1,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
...,...,...,...,...,...,...,...
2986,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [4]:
countries.drop(labels='Denmark', axis=0)

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
Norway,Western Europe,7.392,0.035,7.462,7.323,11.053,0.954,73.300,0.960,0.093,0.270,2.43,1.543,1.108,0.782,0.703,0.249,0.427,2.580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [5]:
countries.drop(index='Denmark')

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
Norway,Western Europe,7.392,0.035,7.462,7.323,11.053,0.954,73.300,0.960,0.093,0.270,2.43,1.543,1.108,0.782,0.703,0.249,0.427,2.580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [6]:
btc.sort_index(ascending=False,inplace=True)

In [7]:
btc.drop(2990)

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
2989,2990,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2988,2989,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2987,2988,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2986,2987,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2985,2986,Bitcoin,BTC,2021-07-01 23:59:59,35035.982712,32883.781226,35035.982712,33572.117653,3.783896e+10,6.293393e+11
...,...,...,...,...,...,...,...,...,...,...
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09

In [8]:
#delete based on index
countries.drop(countries.index[0:3]) #position first three rows

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
Norway,Western Europe,7.392,0.035,7.462,7.323,11.053,0.954,73.300,0.960,0.093,0.270,2.43,1.543,1.108,0.782,0.703,0.249,0.427,2.580
Sweden,Western Europe,7.363,0.036,7.433,7.293,10.867,0.934,72.700,0.945,0.086,0.237,2.43,1.478,1.062,0.763,0.685,0.244,0.448,2.683
Luxembourg,Western Europe,7.324,0.037,7.396,7.252,11.647,0.908,72.600,0.907,-0.034,0.386,2.43,1.751,1.003,0.760,0.639,0.166,0.353,2.653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

In [9]:
countries.index[0:3]

Index(['Finland', 'Denmark', 'Switzerland'], dtype='object', name='Country name')

In [10]:
countries.columns

Index(['Regional indicator', 'Ladder score', 'Standard error of ladder score',
       'upperwhisker', 'lowerwhisker', 'Logged GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [11]:
#Add columns
titanic['species'] = 'human' # all values set to human
houses.insert(0, 'county', 'King County') #pos, colun name, value can be an array
houses

,county,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,King County,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,King County,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,King County,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,King County,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,King County,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,King County,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,King County,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,King County,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,King County,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,King County,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [12]:
houses['sale_price'] = houses['price'] #duplicate values

In [13]:
#Dynamic columns
titanic['num_relatives'] = titanic['sibsp'] + titanic['parch']

In [14]:
titanic.sort_values('num_relatives', ascending=False)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,species,num_relatives
1177,3,0,"Sage, Mr. Frederick",male,?,8,2,CA. 2343,69.55,?,S,?,?,?,human,10
1179,3,0,"Sage, Mr. John George",male,?,1,9,CA. 2343,69.55,?,S,?,?,?,human,10
1173,3,0,"Sage, Miss. Constance Gladys",female,?,8,2,CA. 2343,69.55,?,S,?,?,?,human,10
1170,3,0,"Sage, Master. Thomas Henry",male,?,8,2,CA. 2343,69.55,?,S,?,?,?,human,10
1172,3,0,"Sage, Miss. Ada",female,?,8,2,CA. 2343,69.55,?,S,?,?,?,human,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,2,1,"Wright, Miss. Marion",female,26,0,0,220844,13.5,?,S,9,?,"Yoevil, England / Cottage Grove, OR",human,0
599,2,0,"Yrois, Miss. Henriette ('Mrs Harbeck')",female,24,0,0,248747,13,?,S,?,?,Paris,human,0
600,3,0,"Abbing, Mr. Anthony",male,42,0,0,C.A. 5547,7.55,?,S,?,?,?,human,0
604,3,1,"Abelseth, Miss. Karen Marie",female,16,0,0,348125,7.65,?,S,16,?,"Norway Los Angeles, CA",human,0
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?,human,0

In [15]:
#Highest price per sqft
houses['price_per_sqft'] = houses['price'] / houses['sqft_living']

In [16]:
houses.sort_values('price_per_sqft').tail(50)

,county,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sale_price,price_per_sqft
13528,King County,3025059124,20140828T000000,3168750.0,5,3.50,4330,11979,1.0,0,...,2240,2008,0,98004,47.6251,-122.218,4320,12000,3168750.0,731.812933
16520,King County,9185700414,20140522T000000,1180500.0,3,1.75,1610,7200,1.0,0,...,520,1973,0,98112,47.6279,-122.287,3790,7200,1180500.0,733.229814
14183,King County,2915200210,20141205T000000,500000.0,2,1.00,680,5250,1.0,0,...,0,1922,0,98177,47.7013,-122.359,1620,5461,500000.0,735.294118
21576,King County,9253900271,20150107T000000,3567000.0,5,4.50,4850,10584,2.0,1,...,1310,2007,0,98008,47.5943,-122.110,3470,18270,3567000.0,735.463918
9487,King County,6072800205,20141119T000000,2375000.0,4,2.50,3220,20251,1.0,0,...,0,1969,0,98006,47.5692,-122.192,4200,22114,2375000.0,737.577640
15258,King County,1732800780,20150212T000000,3065000.0,5,3.00,4150,7500,2.5,0,...,640,1909,0,98119,47.6303,-122.362,2250,4050,3065000.0,738.554217
4523,King County,7871500485,20150427T000000,1236000.0,3,1.50,1670,3852,2.0,0,...,0,1928,0,98119,47.6411,-122.371,2320,4572,1236000.0,740.119760
1584,King County,8964800370,20141022T000000,1375000.0,3,1.50,1850,10572,1.0,0,...,0,1953,0,98004,47.6194,-122.208,3030,12752,1375000.0,743.243243
9608,King County,1337800805,20140703T000000,1755000.0,3,2.00,2360,4800,2.0,0,...,0,1909,2014,98112,47.6317,-122.312,2260,4800,1755000.0,743.644068
1846,King County,4083306175,20150401T000000,805000.0,3,1.75,1080,3200,1.0,0,...,200,1926,0,98103,47.6503,-122.338,1780,5200,805000.0,745.370370
15381,King County,2856101479,20140701T000000,276000.0,1,0.75,370,1801,1.0,0,...,0,1923,0,98117,47.6778,-122.389,1340,5000,276000.0,745.945946
14055,King County,369000365,20150422T000000,510000.0,1,1.00,680,6600,1.0,0,...,200,1916,0,98199,47.6567,-122.392,1170,5500,510000.0,750.000000
7311,King County,6072800170,20150428T000000,2500000.0,4,4.00,3330,24354,1.0,0,...,0,1961,0,98006,47.5708,-122.192,3880,25493,2500000.0,750.750751
7319,King County,5101403915,20150403T000000,970000.0,2,1.00,1290,5376,1.0,0,...,0,1945,0,98115,47.6966,-122.315,1180,5376,970000.0,751.937984
3287,King County,9238900855,20150313T000000,700000.0,2,1.00,930,5000,1.0,0,...,0,1926,2013,98136,47.5333,-122.388,1760,5228,700000.0,752.688172
15255,King County,2425049063,20140911T000000,3640900.0,4,3.25,4830,22257,2.0,1,...,0,1990,0,98039,47.6409,-122.241,3820,25582,3640900.0,753.809524
9850,King County,8861000060,20141231T000000,875000.0,3,1.00,1160,10732,1.0,0,...,0,1953,0,98004,47.6391,-122.205,2390,13656,875000.0,754.310345
17302,King County,2513500010,20150504T000000,747000.0,2,1.00,990,4000,1.0,0,...,0,1911,0,98103,47.6589,-122.341,1560,4000,747000.0,754.545455
7017,King County,203100460,20140924T000000,400000.0,1,1.00,530,13679,1.0,0,...,0,1949,0,98053,47.6422,-121.954,1930,20624,400000.0,754.716981
1030,King County,2267000160,20141020T000000,900000.0,4,2.00,1190,8190,1.5,0,...,0,1945,0,98117,47.6908,-122.397,1190,1567,900000.0,756.302521
6823,King County,8964800225,20150303T000000,1430000.0,3,2.00,1890,12017,1.0,0,...,0,1949,0,98004,47.6203,-122.210,2000,12210,1430000.0,756.613757
18174,King County,9528102870,20150304T000000,818900.0,3,1.00,1080,4120,1.0,0,...,100,1919,0,98115,47.6771,-122.319,1280,3090,818900.0,758.240741
18556,King County,6613000930,20140902T000000,2950000.0,4,3.25,3890,25470,2.0,1,...,860,1923,0,98105,47.6608,-122.269,4140,19281,2950000.0,758.354756
8539,King County,9808700650,20150313T000000,1208000.0,3,2.25,1590,8520,2.0,0,...,0,1980,0,98004,47.6477,-122.216,2470,12005,1208000.0,759.748428
6808,King County,3025059136,20140813T000000,800000.0,2,1.00,1050,8750,1.0,0,...,0,1951,0,98004,47.6294,-122.215,3360,20115,800000.0,761.904762
14822,King County,3623500408,20150330T000000,2600000.0,3,3.00,3410,16015,2.0,1,...,1190,1973,0,98040,47.5721,-122.239,3760,16572,2600000.0,762.463343
15039,King County,2726049034,20141110T000000,2000000.0,3,3.25,2610,16387,2.0,1,...,0,2006,0,98125,47.7175,-122.278,2590,12958,2000000.0,766.283525
10072,King County,4221900030,20150501T000000,682000.0,2,1.00,890,5000,1.0,0,...,0,1943,0,98105,47.6666,-122.279,1680,5000,682000.0,766.292135
7530,King County,7228501745,20150219T000000,935000.0,4,2.00,1220,7489,2.0,0,...,0,1903,0,98122,47.6133,-122.306,1220,3750,935000.0,766.393443
4181,King County,7986400945,20141010T000000,775000.0,2,1.00,1010,3600,1.0,0,...,0,1913,0,98107,47.6641,-122.357,1540,3600,775000.0,767.326733
2075,King County,3623500260,20140512T000000,1200000.0,3,1.75,1560,8078,1.5,1,...,0,1928,0,98040,47.5779,-122.246,2890,16710,1200000.0,769.230769
4078,King County,3262300940,20150210T000000,940000.0,3,1.00,1220,8119,1.0,0,...,0,1955,0,98039,47.6328,-122.236,1910,8119,940000.0,770.491803
14799,King County,6684500040,20141202T000000,725000.0,3,1.00,940,8377,1.0,0,...,0,1952,0,98004,47.5974,-122.200,1710,6900,725000.0,771.276596
6402,King County,2624049091,20150313T000000,2903000.0,5,2.50,3750,91681,2.0,1,...,0,1925,0,98118,47.5379,-122.264,3540,24293,2903000.0,774.133333
16252,King County,3760500280,20141014T000000,1950000.0,3,2.50,2510,12779,1.5,0,...,0,1968,0,98034,47.6982,-122.231,2810,12225,1950000.0,776.892430
8337,King County,2770604925,20140715T000000,1300000.0,5,1.00,1670,6400,1.5,0,...,0,1919,0,98119,47.6542,-122.373,1910,2983,1300000.0,778.443114
9294,King County,1257201095,20150323T000000,826000.0,2,1.00,1060,6120,1.0,0,...,0,1908,0,98103,47.6739,-122.329,1730,4080,826000.0,779.245283
656,King County,3760500116,20141120T000000,3070000.0,3,2.50,3930,55867,1.0,1,...,1600,1957,0,98034,47.7022,-122.224,2730,26324,3070000.0,781.170483
18199,King County,3625059152,20141230T000000,3300000.0,3,3.25,4220,41300,1.0,1,...,1760,1958,1987,98008,47.6083,-122.110,3810,30401,3300000.0,781.990521
7432,King County,5316100780,20140922T000000,2575000.0,4,3.50,3280,3800,2.0,0,...,400,2011,0,98112,47.6299,-122.280,2050,3800,2575000.0,785.060976
18876,King County,9808700025,20150211T000000,1500000.0,3,1.50,1910,21374,1.0,0,...,0,1955,0,98004,47.6453,-122.214,2850,16167,1500000.0,785.340314
12757,King County,2767603026,20150415T000000,425000.0,2,1.00,540,2500,1.0,0,...,0,1905,0,98107,47.6729,-122.383,1290,5000,425000.0,787.037037
6243,King County,5536100010,20150204T000000,1050000.0,4,1.00,1330,9729,1.0,0,...,0,1952,0,98004,47.6223,-122.208,2920,10353,1050000.0,789.473684
7313,King County,4131900066,20140825T000000,3100000.0,3,3.00,3920,13085,2.0,1,...,0,1996,0,98040,47.5716,-122.204,3450,13287,3100000.0,790.816327
18597,King County,3222049087,20150422T000000,570000.0,1,1.00,720,7540,1.0,1,...,0,1905,0,98198,47.3509,-122.323,1120,9736,570000.0,791.666667
9314,King County,4389200610,20141201T000000,903000.0,2,1.50,1140,7800,1.0,0,...,0,1947,0,98004,47.6142,-122.209,2020,7800,903000.0,792.105263
8623,King County,6303400395,20150130T000000,325000.0,1,0.75,410,8636,1.0,0,...,0,1953,0,98146,47.5077,-122.357,1190,8636,325000.0,792.682927
10446,King County,1118000320,20150508T000000,3400000.0,4,4.00,4260,11765,2.0,0,...,980,1939,2010,98112,47.6380,-122.288,4260,10408,3400000.0,798.122066
4013,King County,724069059,20140509T000000,2400000.0,3,2.25,3000,11665,1.5,1,...,0,2001,0,98075,47.5884,-122.086,3000,15959,2400000.0,800.000000
19336,King County,6021500970,20150407T000000,874950.0,2,1.00,1080,4000,1.0,0,...,0,1940,0,98117,47.6902,-122.387,1530,4240,874950.0,810.138889

In [17]:
houses.sort_values('price_per_sqft').tail(50)['zipcode'].value_counts()

zipcode
98004    10
98112     4
98040     3
98119     3
98103     3
98117     3
98034     2
98107     2
98105     2
98039     2
98115     2
98006     2
98008     2
98136     1
98053     1
98199     1
98125     1
98122     1
98118     1
98177     1
98198     1
98146     1
98075     1
Name: count, dtype: int64

In [18]:
btc.set_index('Date')

,SNo,Name,Symbol,High,Low,Open,Close,Volume,Marketcap
Date,,,,,,,,,
2021-07-06 23:59:59,2991,Bitcoin,BTC,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11
2021-07-05 23:59:59,2990,Bitcoin,BTC,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2021-07-04 23:59:59,2989,Bitcoin,BTC,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2021-07-03 23:59:59,2988,Bitcoin,BTC,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2021-07-02 23:59:59,2987,Bitcoin,BTC,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
...,...,...,...,...,...,...,...,...,...
2013-05-03 23:59:59,5,Bitcoin,BTC,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
2013-05-02 23:59:59,4,Bitcoin,BTC,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
2013-05-01 23:59:59,3,Bitcoin,BTC,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
2013-04-30 23:59:59,2,Bitcoin,BTC,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2013-04-29 23:59:59,1,Bitcoin,BTC,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09

In [19]:
btc['change'] = btc['Close'] - btc['Open']
btc.sort_values('change', ascending=False)

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,change
2842,2843,Bitcoin,BTC,2021-02-08 23:59:59,46203.931437,38076.322807,38886.827290,46196.463719,1.014672e+11,8.603427e+11,7309.636429
2919,2920,Bitcoin,BTC,2021-04-26 23:59:59,54288.002155,48852.796843,49077.792363,54021.754787,5.828404e+10,1.009780e+12,4943.962424
2863,2864,Bitcoin,BTC,2021-03-01 23:59:59,49784.015290,45115.093115,45159.503053,49631.241371,5.389130e+10,9.252355e+11,4471.738318
2853,2854,Bitcoin,BTC,2021-02-19 23:59:59,56113.650547,50937.275722,51675.981285,55888.133682,6.349550e+10,1.041381e+12,4212.152397
2923,2924,Bitcoin,BTC,2021-04-30 23:59:59,57900.719988,53129.600877,53568.663584,57750.177346,5.239593e+10,1.079670e+12,4181.513762
...,...,...,...,...,...,...,...,...,...,...,...
2911,2912,Bitcoin,BTC,2021-04-18 23:59:59,61057.456509,52829.535926,60701.886093,56216.185002,9.746887e+10,1.050445e+12,-4485.701091
2824,2825,Bitcoin,BTC,2021-01-21 23:59:59,35552.679497,30250.749639,35549.397409,30825.698506,7.564307e+10,5.735657e+11,-4723.698903
2857,2858,Bitcoin,BTC,2021-02-23 23:59:59,54204.929756,45290.590268,54204.929756,48824.426869,1.061025e+11,9.099259e+11,-5380.502887
2942,2943,Bitcoin,BTC,2021-05-19 23:59:59,43546.116485,30681.496912,42944.975447,37002.440466,1.263581e+11,6.924526e+11,-5942.534981
2935,2936,Bitcoin,BTC,2021-05-12 23:59:59,57939.362415,49150.533875,56714.533167,49150.533875,7.521540e+10,9.195278e+11,-7563.999292

In [21]:
#Rename columns
mapper = {'Regional indicator': 'regional_indicator', 'Ladder score': 'ladder_score'}
countries.rename(columns=mapper) #index={} for labels or use axis with first argument passed

,regional_indicator,ladder_score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
Country name,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895