In [37]:
import pandas as pd
houses = pd.read_csv('../data/kc_house_data.csv')
titanic = pd.read_csv('../data/titanic.csv')
netflix = pd.read_csv('../data/netflix_titles.csv', sep='|', index_col=0)
btc = pd.read_csv('../data/coin_Bitcoin.csv')
countries = pd.read_csv('../data/world-happiness-report-2021.csv', index_col=0)

In [38]:
titanic['sex'].replace(['female', 'male'], ['F', 'M']) #Series.replace

0       F
1       M
2       F
3       M
4       F
       ..
1304    F
1305    F
1306    M
1307    M
1308    M
Name: sex, Length: 1309, dtype: object

In [39]:
titanic['sex'].replace('?', 'idk')  #titanic['sex'].replace('?', None)  does not work as expected use list
#titanic['sex'].replace(['?'], [None], inplace=True)no longer works  #value counts does not include none but using dropna=False gets them
titanic['age'] = titanic['age'].replace(['?'], [None]) #titanic.replace({'age': {'?': None}}, inplace=True

In [40]:
titanic.head(50)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48,0,0,19952,26.55,E12,S,3,?,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S,10,?,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0,A36,S,?,?,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53,2,0,11769,51.4792,C101,S,D,?,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71,0,0,PC 17609,49.5042,?,C,?,22,"Montevideo, Uruguay"
10,1,0,"Astor, Col. John Jacob",male,47,1,0,PC 17757,227.525,C62 C64,C,?,124,"New York, NY"
11,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18,1,0,PC 17757,227.525,C62 C64,C,4,?,"New York, NY"
12,1,1,"Aubart, Mme. Leontine Pauline",female,24,0,0,PC 17477,69.3,B35,C,9,?,"Paris, France"
13,1,1,"Barber, Miss. Ellen 'Nellie'",female,26,0,0,19877,78.85,?,S,6,?,?
14,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80,0,0,27042,30,A23,S,B,?,"Hessle, Yorks"
15,1,0,"Baumann, Mr. John D",male,None,0,0,PC 17318,25.925,?,S,?,?,"New York, NY"
16,1,0,"Baxter, Mr. Quigg Edmond",male,24,0,1,PC 17558,247.5208,B58 B60,C,?,?,"Montreal, PQ"
17,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50,0,1,PC 17558,247.5208,B58 B60,C,6,?,"Montreal, PQ"
18,1,1,"Bazzani, Miss. Albina",female,32,0,0,11813,76.2917,D15,C,8,?,?
19,1,0,"Beattie, Mr. Thomson",male,36,0,0,13050,75.2417,C6,C,A,?,"Winnipeg, MN"
20,1,1,"Beckwith, Mr. Richard Leonard",male,37,1,1,11751,52.5542,D35,S,5,?,"New York, NY"
21,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47,1,1,11751,52.5542,D35,S,5,?,"New York, NY"
22,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C,5,?,"New York, NY"
23,1,1,"Bidois, Miss. Rosalie",female,42,0,0,PC 17757,227.525,?,C,4,?,?
24,1,1,"Bird, Miss. Ellen",female,29,0,0,PC 17483,221.7792,C97,S,8,?,?
25,1,0,"Birnbaum, Mr. Jakob",male,25,0,0,13905,26,?,C,?,148,"San Francisco, CA"
26,1,1,"Bishop, Mr. Dickinson H",male,25,1,0,11967,91.0792,B49,C,7,?,"Dowagiac, MI"
27,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19,1,0,11967,91.0792,B49,C,7,?,"Dowagiac, MI"
28,1,1,"Bissette, Miss. Amelia",female,35,0,0,PC 17760,135.6333,C99,S,8,?,?
29,1,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28,0,0,110564,26.55,C52,S,D,?,"Stockholm, Sweden / Washington, DC"
30,1,0,"Blackwell, Mr. Stephen Weart",male,45,0,0,113784,35.5,T,S,?,?,"Trenton, NJ"
31,1,1,"Blank, Mr. Henry",male,40,0,0,112277,31,A31,C,7,?,"Glen Ridge, NJ"
32,1,1,"Bonnell, Miss. Caroline",female,30,0,0,36928,164.8667,C7,S,8,?,"Youngstown, OH"
33,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S,8,?,"Birkdale, England Cleveland, Ohio"
34,1,0,"Borebank, Mr. John James",male,42,0,0,110489,26.55,D22,S,?,?,"London / Winnipeg, MB"
35,1,1,"Bowen, Miss. Grace Scott",female,45,0,0,PC 17608,262.375,?,C,4,?,"Cooperstown, NY"
36,1,1,"Bowerman, Miss. Elsie Edith",female,22,0,1,113505,55,E33,S,6,?,"St Leonards-on-Sea, England Ohio"
37,1,1,"Bradley, Mr. George ('George Arthur Brayton')",male,None,0,0,111427,26.55,?,S,9,?,"Los Angeles, CA"
38,1,0,"Brady, Mr. John Bertram",male,41,0,0,113054,30.5,A21,S,?,?,"Pomeroy, WA"
39,1,0,"Brandeis, Mr. Emil",male,48,0,0,PC 17591,50.4958,B10,C,?,208,"Omaha, NE"
40,1,0,"Brewe, Dr. Arthur Jackson",male,None,0,0,112379,39.6,?,C,?,?,"Philadelphia, PA"
41,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44,0,0,PC 17610,27.7208,B4,C,6,?,"Denver, CO"
42,1,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59,2,0,11769,51.4792,C101,S,D,?,"Belmont, MA"
43,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60,0,0,11813,76.2917,D15,C,8,?,"Philadelphia, PA"
44,1,1,"Burns, Miss. Elizabeth Margaret",female,41,0,0,16966,134.5,E40,C,3,?,?
45,1,0,"Butt, Major. Archibald Willingham",male,45,0,0,113050,26.55,B38,S,?,?,"Washington, DC"
46,1,0,"Cairns, Mr. Alexander",male,None,0,0,113798,31,?,S,?,?,?
47,1,1,"Calderhead, Mr. Edward Pennington",male,42,0,0,PC 17476,26.2875,E24,S,5,?,"New York, NY"
48,1,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53,0,0,PC 17606,27.4458,?,C,6,?,"Washington, DC"
49,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C,3,?,"Austria-Hungary / Germantown, Philadelphia, PA"

In [41]:
countries.loc[['Denmark'], ['Ladder score']]

              Ladder score
Country name
Denmark               7.62

In [42]:
countries.loc[['Denmark', 'Norway', 'Sweden'], ['Regional indicator']] = 'Scandinavia'

In [43]:
countries.loc[['Denmark', 'Norway', 'Sweden'], ['Regional indicator']]

             Regional indicator
Country name
Denmark             Scandinavia
Norway              Scandinavia
Sweden              Scandinavia

In [44]:
countries.loc[['Denmark', 'Norway', 'Sweden', 'Iceland'], ['Regional indicator']]
#countries.loc['Finland'] = 'LOL' sets all columns to LOL, countries.loc['Finland', ['col1', 'col2']] = 'value' sets given columns to value
#houses[['bedrooms', 'bathrooms']]

             Regional indicator
Country name
Denmark             Scandinavia
Norway              Scandinavia
Sweden              Scandinavia
Iceland          Western Europe

In [45]:
countries.loc[['Denmark', 'Norway', 'Sweden', 'Iceland'], ['Regional indicator', 'is_cold']] = ['Nordic', 'yes'] #all other rows have Nan for newly added column
countries

,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,is_cold
Country name,,,,,,,,,,,,,,,,,,,,
Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253,NaN
Denmark,Nordic,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868,yes
Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839,NaN
Iceland,Nordic,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967,yes
Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800,NaN
Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648,NaN
Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095,NaN
Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205,NaN
Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895,NaN

In [46]:
#Boolean masks in updates
many_rooms = houses['bedrooms'] >= 10
#houses.loc[many_rooms, ['bedrooms']] = 'too many!'  cast data beforeassignment
# Convert the whole column to string type first
#houses['bedrooms'] = houses['bedrooms'].astype(str)

# Now you can safely insert string values
#houses.loc[many_rooms, 'bedrooms'] = 'too many!'

In [48]:
houses['luxury_level'] = "normal"
houses

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,luxury_level
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,normal
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,normal
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,normal
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,normal
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,1530,0,2009,0,98103,47.6993,-122.346,1530,1509,normal
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,2310,0,2014,0,98146,47.5107,-122.362,1830,7200,normal
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,1020,0,2009,0,98144,47.5944,-122.299,1020,2007,normal
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,1600,0,2004,0,98027,47.5345,-122.069,1410,1287,normal
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,1020,0,2008,0,98144,47.5941,-122.299,1020,1357,normal

In [50]:
great_views = houses['view'] == 4
high_quality = houses['grade'] > 12
houses.loc[great_views & high_quality, ['luxury_level']] = 'ultra'

In [52]:
houses.luxury_level.value_counts()

luxury_level
normal    21610
ultra         3
Name: count, dtype: int64