In [1]:
import pandas as pd
bestsellers = pd.read_csv('../data/bestsellers.csv')
bestsellers.min()

Name           10-Day Green Smoothie Cleanse
Author                      Abraham Verghese
User Rating                              3.3
Reviews                                   37
Price                                      0
Year                                    2009
Genre                                Fiction
dtype: object

In [2]:
bestsellers.max()

Name           You Are a Badass: How to Stop Doubting Your Gr...
Author                                              Zhi Gang Sha
User Rating                                                  4.9
Reviews                                                    87841
Price                                                        105
Year                                                        2019
Genre                                                Non Fiction
dtype: object

In [4]:
bestsellers.mean(numeric_only=True)

User Rating        4.618364
Reviews        11953.281818
Price             13.100000
Year            2014.000000
dtype: float64

In [10]:
bestsellers.median(numeric_only=True)

User Rating       4.7
Reviews        8580.0
Price            11.0
Year           2014.0
dtype: float64

In [7]:
bestsellers.mode()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,Publication Manual of the American Psychologic...,Jeff Kinney,4.8,8580.0,8.0,2009,Non Fiction
1,NaN,NaN,NaN,NaN,NaN,2010,NaN
2,NaN,NaN,NaN,NaN,NaN,2011,NaN
3,NaN,NaN,NaN,NaN,NaN,2012,NaN
4,NaN,NaN,NaN,NaN,NaN,2013,NaN
5,NaN,NaN,NaN,NaN,NaN,2014,NaN
6,NaN,NaN,NaN,NaN,NaN,2015,NaN
7,NaN,NaN,NaN,NaN,NaN,2016,NaN
8,NaN,NaN,NaN,NaN,NaN,2017,NaN
9,NaN,NaN,NaN,NaN,NaN,2018,NaN
10,NaN,NaN,NaN,NaN,NaN,2019,NaN

In [8]:
bestsellers.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [9]:
bestsellers.describe(include=['object', 'int64'])

,Name,Author,Reviews,Price,Year,Genre
count,550,550,550.000000,550.000000,550.000000,550
unique,351,248,NaN,NaN,NaN,2
top,Publication Manual of the American Psychologic...,Jeff Kinney,NaN,NaN,NaN,Non Fiction
freq,10,12,NaN,NaN,NaN,310
mean,NaN,NaN,11953.281818,13.100000,2014.000000,NaN
std,NaN,NaN,11731.132017,10.842262,3.165156,NaN
min,NaN,NaN,37.000000,0.000000,2009.000000,NaN
25%,NaN,NaN,4058.000000,7.000000,2011.000000,NaN
50%,NaN,NaN,8580.000000,11.000000,2014.000000,NaN
75%,NaN,NaN,17253.250000,16.000000,2017.000000,NaN
max,NaN,NaN,87841.000000,105.000000,2019.000000,NaN

In [11]:
bestsellers.sum()

Name           10-Day Green Smoothie Cleanse11/22/63: A Novel...
Author         JJ SmithStephen KingJordan B. PetersonGeorge O...
User Rating                                               2540.1
Reviews                                                  6574305
Price                                                       7205
Year                                                     1107700
Genre          Non FictionFictionNon FictionFictionNon Fictio...
dtype: object