In [2]:
import pandas as pd

tweets = pd.read_csv('../data/JoeBidenTweets.csv')
tweets.set_index('id', inplace=True)

In [3]:
tweets.drop(['url'], axis=1) #tweets.drop(columns='url')

,timestamp,tweet,replies,retweets,quotes,likes
id,,,,,,
361388562,2007-10-24 22:45,Tune in 11:30 ET tomorrow for a live webcast o...,19,5,17,11
543984392,2007-12-29 15:35,"Iowans, there's a good chance there's a Biden ...",13,16,6,22
189287227321356289,2012-04-09 09:42,We're excited to announce that @JoeBiden is be...,21,82,1,20
189287350034104320,2012-04-09 09:43,Campaign staff will run this account to keep y...,144,76,37,51
189339650610036736,2012-04-09 13:11,News for you this morning: VP Biden will speak...,10,54,0,5
...,...,...,...,...,...,...
1322865972819251200,2020-11-01 11:40,"As president, I’ll build an economy that rewar...",3085,3654,480,36995
1322871257902145536,2020-11-01 12:01,Let’s put dogs back in the White House. https:...,2211,4211,1246,34240
1322876039144636417,2020-11-01 12:20,We have in our hands the ultimate power: the p...,918,1143,122,6954
1322881072363917312,2020-11-01 12:40,"We need to:\n\nBuild bridges, not walls.\nOpen...",1281,2255,344,16696
1322886357535150081,2020-11-01 13:01,Jodie –– you have my word: I will always stand...,168,270,37,1648

In [5]:
tweets.drop(361388562) #tweets.drop(index=361388562)

,timestamp,url,tweet,replies,retweets,quotes,likes
id,,,,,,,
543984392,2007-12-29 15:35,https://twitter.com/JoeBiden/status/543984392,"Iowans, there's a good chance there's a Biden ...",13,16,6,22
189287227321356289,2012-04-09 09:42,https://twitter.com/JoeBiden/status/1892872273...,We're excited to announce that @JoeBiden is be...,21,82,1,20
189287350034104320,2012-04-09 09:43,https://twitter.com/JoeBiden/status/1892873500...,Campaign staff will run this account to keep y...,144,76,37,51
189339650610036736,2012-04-09 13:11,https://twitter.com/JoeBiden/status/1893396506...,News for you this morning: VP Biden will speak...,10,54,0,5
189343279140184065,2012-04-09 13:25,https://twitter.com/JoeBiden/status/1893432791...,"In NH on 4/12, the Vice President will give hi...",16,52,0,6
...,...,...,...,...,...,...,...
1322865972819251200,2020-11-01 11:40,https://twitter.com/JoeBiden/status/1322865972...,"As president, I’ll build an economy that rewar...",3085,3654,480,36995
1322871257902145536,2020-11-01 12:01,https://twitter.com/JoeBiden/status/1322871257...,Let’s put dogs back in the White House. https:...,2211,4211,1246,34240
1322876039144636417,2020-11-01 12:20,https://twitter.com/JoeBiden/status/1322876039...,We have in our hands the ultimate power: the p...,918,1143,122,6954
1322881072363917312,2020-11-01 12:40,https://twitter.com/JoeBiden/status/1322881072...,"We need to:\n\nBuild bridges, not walls.\nOpen...",1281,2255,344,16696
1322886357535150081,2020-11-01 13:01,https://twitter.com/JoeBiden/status/1322886357...,Jodie –– you have my word: I will always stand...,168,270,37,1648

In [6]:
tweets['user'] = 'Joe Biden'
tweets['ratio'] = tweets['replies'] / tweets['retweets']

In [7]:
tweets.ratio.sort_values(ascending=False)

id
232971730119950338     10.000000
1200882191875465216     8.239745
1150774078233387008     7.745342
1186989582182694922     6.194940
1189327302733238272     5.852217
                         ...
202779651985256450      0.000000
190826443322818561      0.000000
225726112607645697      0.000000
195176336346710016      0.000000
194450021532442628      0.000000
Name: ratio, Length: 6064, dtype: float64

In [9]:
tweets['interactions'] = tweets['replies'] +  tweets['retweets'] + tweets['quotes'] + tweets['likes']

In [10]:
tweets['interactions'].sort_values(ascending=False)

id
1311120831032909825    2293793
1253751812194070529    2073072
1317978773707345920    1612157
1318170176660135936    1494296
1312460408192724992    1323850
                        ...
195569465834999809          13
195966131255787521          13
190198707449372673          12
218029226446688256          11
194529576205025281           9
Name: interactions, Length: 6064, dtype: int64